Repository momentum-design/momentum-ui, pull requests merged in 2020-12, with the labels that each got.

#708 fix(Phone-input): CAX-822
  web-components/src/[sandbox]/examples/phone-input.ts
  web-components/src/components/combobox/ComboBox.ts
  web-components/src/components/combobox/scss/combobox.scss
  web-components/src/components/phone-input/PhoneInput.ts
  web-components/src/components/phone-input/scss/module.scss
  web-components/src/components/phone-input/scss/phoneInput.scss
  web-components/src/components/phone-input/scss/settings.scss
  web-components/src/components/phone-input/tokens/lm-phone-input-tokens.js
  web-components/src/components/phone-input/tokens/md-phone-input-tokens.js
Labels: bug

#706 feat(floating-modal): rewrite floating modal using interactjs
  web-components/package.json
  web-components/src/[sandbox]/examples/floating-modal.ts
  web-components/src/[sandbox]/examples/index.ts
  web-components/src/[sandbox]/sandbox.ts
  web-components/src/components/floating-modal/FloatingModal.stories.ts
  web-components/src/components/floating-modal/FloatingModal.test.ts
  web-components/src/components/floating-modal/FloatingModal.ts
  web-components/src/components/floating-modal/scss/floating.scss
  web-components/src/components/floating-modal/scss/settings.scss
Labels: REVIEW, dependencies, enhancement

#694 feat(DatePicker): New date picker component
  web-components/package.json
  web-components/src/[sandbox]/examples/datepicker.ts
  web-components/src/[sandbox]/examples/index.ts
  web-components/src/[sandbox]/sandbox.ts
  web-components/src/components/datepicker/DatePicker.stories.ts
  web-components/src/components/datepicker/DatePicker.test.ts
  web-components/src/components/datepicker/DatePicker.ts
  web-components/src/components/datepicker/datepicker-calendar/DatePickerCalendar.test.ts
  web-components/src/components/datepicker/datepicker-calendar/DatePickerCalendar.ts
  web-components/src/components/datepicker/datepicker-day/DatePickerDay.test.ts
  web-components/src/components/datepicker/datepicker-day/DatePickerDay.ts
  web-components/src/components/datepicker/datepicker-month/DatePickerMonth.test.ts
  web-components/src/components/datepicker/datepicker-month/DatePickerMonth.ts
  web-components/src/components/datepicker/datepicker-week/DatePickerWeek.test.ts
  web-components/src/components/datepicker/datepicker-week/DatePickerWeek.ts
  web-components/src/components/datepicker/scss/datepicker.scss
  web-components/src/components/datepicker/scss/module.scss
  web-components/src/components/datepicker/scss/settings.scss
  web-components/src/components/datepicker/tokens/lm-datepicker-tokens.js
  web-components/src/components/datepicker/tokens/md-datepicker-tokens.js
  web-components/src/index.ts
  web-components/src/utils/dateUtils.test.ts
  web-components/src/utils/dateUtils.ts
Labels: WIP, new component

#715 feat(combobox): improve search matching
  web-components/src/[sandbox]/examples/combobox.ts
  web-components/src/[sandbox]/sandbox.ts
  web-components/src/components/combobox/ComboBox.stories.ts
  web-components/src/components/combobox/ComboBox.ts
Labels: enhancement

#712 New Component: Time Picker
  web-components/src/[sandbox]/examples/index.ts
  web-components/src/[sandbox]/examples/timepicker.ts
  web-components/src/[sandbox]/sandbox.ts
  web-components/src/components/combobox/ComboBox.ts
  web-components/src/components/input/Input.ts
  web-components/src/components/input/scss/input.scss
  web-components/src/components/timepicker/TimePicker.stories.ts
  web-components/src/components/timepicker/TimePicker.test.ts
  web-components/src/components/timepicker/TimePicker.ts
  web-components/src/components/timepicker/scss/module.scss
  web-components/src/components/timepicker/scss/settings.scss
  web-components/src/components/timepicker/scss/timepicker.scss
  web-components/src/constants.ts
  web-components/src/utils/validations.ts
Labels: REVIEW

#701 feat(accordion): create accordion component
  web-components/src/[sandbox]/examples/accordion.ts
  web-components/src/[sandbox]/examples/index.ts
  web-components/src/[sandbox]/sandbox.ts
  web-components/src/components/accordion/Accordion.stories.ts
  web-components/src/components/accordion/Accordion.test.ts
  web-components/src/components/accordion/Accordion.ts
  web-components/src/components/accordion/AccordionItem.test.ts
  web-components/src/components/accordion/AccordionItem.ts
  web-components/src/components/accordion/scss/accordion-item.scss
  web-components/src/components/accordion/scss/accordion.scss
  web-components/src/components/accordion/scss/mixins.scss
  web-components/src/components/accordion/scss/module.scss
  web-components/src/components/accordion/scss/settings.scss
  web-components/src/components/accordion/tokens/lm-accordion-tokens.js
  web-components/src/components/accordion/tokens/md-accordion-tokens.js
Labels: REVIEW, new component

#728 feat(tooltip): add "opened" property to have ability manually close/open tooltip
  web-components/src/components/tooltip/Tooltip.stories.ts
  web-components/src/components/tooltip/Tooltip.test.ts
  web-components/src/components/tooltip/Tooltip.ts
Labels: enhancement

#736 fix(floating-modal): fix bug with modal repositioning
  web-components/src/[sandbox]/examples/floating-modal.ts
  web-components/src/components/floating-modal/FloatingModal.ts
Labels: REVIEW, bug

#720 feat(pagination): create pagination component
  web-components/src/[sandbox]/examples/index.ts
  web-components/src/[sandbox]/examples/pagination.ts
  web-components/src/[sandbox]/sandbox.ts
  web-components/src/components/pagination/Pagination.stories.ts
  web-components/src/components/pagination/Pagination.test.ts
  web-components/src/components/pagination/Pagination.ts
  web-components/src/components/pagination/scss/mixins.scss
  web-components/src/components/pagination/scss/module.scss
  web-components/src/components/pagination/scss/pagination.scss
  web-components/src/components/pagination/scss/settings.scss
  web-components/src/components/pagination/tokens/lm-pagination-tokens.js
  web-components/src/components/pagination/tokens/md-pagination-tokens.js
  web-components/src/index.ts
Labels: REVIEW, new component

#735 feat(theme): add custom event when theme changes
  web-components/src/components/theme/Theme.ts
Labels: enhancement
