Repository momentum-design/momentum-ui, pull requests merged in 2020-11, with the labels that each got.

#654 fix(EditableTextfield): Inline display styles lint error
  web-components/src/components/editable-textfield/EditableTextfield.ts
Labels: bug

#663 fix(Theme): Color token updates CAX-708
  web-components/src/components/taskitem/tokens/lm-taskitem-tokens.js
  web-components/src/wc_scss/settings/avatar.scss
  web-components/src/wc_scss/themes/global--dark.scss
  web-components/src/wc_scss/themes/global--light.scss
Labels: bug

#671 fix(components): fix autofocus handle strategy by mixin
  web-components/src/[sandbox]/examples/menu-overlay.ts
  web-components/src/[sandbox]/examples/modal.ts
  web-components/src/components/input/Input.ts
  web-components/src/components/menu-overlay/MenuOverlay.ts
  web-components/src/components/modal/Modal.test.ts
  web-components/src/components/modal/Modal.ts
  web-components/src/mixins/FocusTrapMixin.test.ts
  web-components/src/mixins/FocusTrapMixin.ts
Labels: REVIEW, bug, enhancement

#670 perf(mixin): improve resize observer performance
  web-components/src/components/modal/Modal.test.ts
  web-components/src/mixins/ResizeMixin.ts
Labels: REVIEW, enhancement

#673 fix(Editable Textfield): Prevent "." in decimal, allow caret placement
  web-components/src/components/editable-textfield/EditableTextfield.ts
Labels: bug

#674 fix(Help Text): Help Text Message Formatting Fix CAX-785
  web-components/src/components/help-text/scss/help-text.scss
  web-components/src/components/help-text/scss/mixins.scss
  web-components/src/components/help-text/scss/settings.scss
Labels: bug

#680 fix(mixin): fix issue with tabbing in sequentially and click focusable new elements
  web-components/src/[sandbox]/examples/modal.ts
  web-components/src/components/combobox/ComboBox.ts
  web-components/src/components/menu-overlay/MenuOverlay.test.ts
  web-components/src/components/menu-overlay/MenuOverlay.ts
  web-components/src/components/tabs/Tab.test.ts
  web-components/src/components/tabs/Tab.ts
  web-components/src/components/tabs/tokens/md-tabs-tokens.js
  web-components/src/mixins/FocusMixin.test.ts
  web-components/src/mixins/FocusMixin.ts
  web-components/src/mixins/FocusTrapMixin.test.ts
  web-components/src/mixins/FocusTrapMixin.ts
Labels: REVIEW, bug, enhancement

#688 fix(tab): fix background for disabled tab
  web-components/src/components/tabs/scss/tab.scss
Labels: bug

#690 fix(Editable Textfield): remove flexbox settings
  web-components/src/components/editable-textfield/scss/editable-textfield.scss
Labels: bug

#687 fix(mixin): wait until initial provided element receive focus
  web-components/src/components/menu-overlay/MenuOverlay.ts
  web-components/src/components/modal/Modal.ts
  web-components/src/mixins/FocusTrapMixin.test.ts
  web-components/src/mixins/FocusTrapMixin.ts
Labels: REVIEW, bug

#686 fix(components): bugfix high contrast
  web-components/src/components/slider/scss/settings.scss
  web-components/src/components/slider/scss/slider.scss
  web-components/src/components/toggle-switch/scss/toggle-switch.scss
Labels: bug

#689 fix(tooltip): tooltip will be cut off at the limits of the innermost element with hidden overflow
  web-components/src/[sandbox]/examples/menu-overlay.ts
  web-components/src/components/theme/Theme.test.ts
  web-components/src/components/theme/Theme.ts
  web-components/src/components/tooltip/Tooltip.test.ts
  web-components/src/components/tooltip/Tooltip.ts
  web-components/src/components/tooltip/scss/tooltip.scss
Labels: bug, enhancement

#667 feat(components): add table component
  web-components/package.json
  web-components/src/[sandbox]/examples/index.ts
  web-components/src/[sandbox]/examples/table.ts
  web-components/src/[sandbox]/sandbox.ts
  web-components/src/components/table/Table.stories.ts
  web-components/src/components/table/Table.test.ts
  web-components/src/components/table/Table.ts
  web-components/src/components/table/scss/module.scss
  web-components/src/components/table/scss/settings.scss
  web-components/src/components/table/scss/table.scss
  web-components/src/components/table/tokens/lm-table-tokens.js
  web-components/src/components/table/tokens/md-table-tokens.js
  web-components/src/index.ts
  web-components/stats/cssStats.js
  web-components/stats/stats-loader.js
Labels: new component

#681 feat(breadcrumb): create breadcrumb component
  web-components/src/[sandbox]/examples/breadcrumb.ts
  web-components/src/[sandbox]/examples/index.ts
  web-components/src/[sandbox]/sandbox.mock.ts
  web-components/src/[sandbox]/sandbox.ts
  web-components/src/components/breadcrumb/Breadcrumb.stories.ts
  web-components/src/components/breadcrumb/Breadcrumb.test.ts
  web-components/src/components/breadcrumb/Breadcrumb.ts
  web-components/src/components/breadcrumb/scss/breadcrumb.scss
  web-components/src/components/breadcrumb/scss/mixins.scss
  web-components/src/components/breadcrumb/scss/module.scss
  web-components/src/components/breadcrumb/scss/settings.scss
  web-components/src/components/breadcrumb/tokens/lm-breadcrumb-token.js
  web-components/src/components/breadcrumb/tokens/md-breadcrumb-token.js
Labels: new component

#697 docs(sandbox): sort sandbox alphabetically
  web-components/src/[sandbox]/examples/checkbox.ts
  web-components/src/[sandbox]/examples/chip.ts
  web-components/src/[sandbox]/examples/editable-field.ts
  web-components/src/[sandbox]/examples/menu-overlay.ts
  web-components/src/[sandbox]/examples/phone-input.ts
  web-components/src/[sandbox]/examples/progress-bar.ts
  web-components/src/[sandbox]/examples/slider.ts
  web-components/src/[sandbox]/sandbox.ts
  web-components/src/components/activity-button/ActivityButton.stories.ts
  web-components/src/components/alert-banner/AlertBanner.stories.ts
  web-components/src/components/alert/Alert.stories.ts
  web-components/src/components/badge/Badge.stories.ts
  web-components/src/components/chip/Chip.stories.ts
  web-components/src/components/editable-textfield/EditableTextfield.stories.ts
  web-components/src/components/icon/Icon.stories.ts
  web-components/src/components/input/Input.stories.ts
  web-components/src/components/label/Label.stories.ts
  web-components/src/components/link/Link.stories.ts
  web-components/src/components/loading/Loading.stories.ts
  web-components/src/components/meeting-alert/MeetingAlert.stories.ts
  web-components/src/components/menu-overlay/MenuOverlay.stories.ts
  web-components/src/components/progress-bar/ProgressBar.stories.ts
  web-components/src/components/taskitem/TaskItem.stories.ts
  web-components/src/components/tooltip/Tooltip.stories.ts
Labels: REVIEW, docs

#704 fix(Editable-Textfield): Missing max-lines feature: CAX-830
  web-components/src/components/editable-textfield/EditableTextfield.ts
Labels: bug
