Repository momentum-design/momentum-ui, pull requests merged in 2021-02, with the labels that each got.

#757 fix(checkbox/radio): fix checkbox/radio-group focus
  web-components/src/[sandbox]/examples/radio-group.ts
  web-components/src/components/checkbox/scss/checkbox.scss
  web-components/src/components/checkbox/scss/module.scss
  web-components/src/components/checkbox/scss/settings.scss
  web-components/src/components/label/scss/module.scss
  web-components/src/components/radio/Radio.ts
  web-components/src/components/radio/scss/mixins.scss
  web-components/src/components/radio/scss/module.scss
  web-components/src/components/radio/scss/radio.scss
  web-components/src/components/radio/scss/radiogroup.scss
  web-components/src/components/radio/scss/settings.scss
Labels: REVIEW

#748 feat(button group): create button group component
  web-components/src/[sandbox]/examples/button-group.ts
  web-components/src/[sandbox]/examples/index.ts
  web-components/src/[sandbox]/sandbox.ts
  web-components/src/components/button-group/ButtonGroup.stories.ts
  web-components/src/components/button-group/ButtonGroup.test.ts
  web-components/src/components/button-group/ButtonGroup.ts
  web-components/src/components/button-group/scss/button-group.scss
  web-components/src/components/button-group/scss/module.scss
  web-components/src/components/button-group/scss/settings.scss
  web-components/src/components/button-group/tokens/lm-button-group-tokens.js
  web-components/src/components/button-group/tokens/md-button-group-tokens.js
  web-components/src/index.ts
Labels: REVIEW, new component

#759 feat(form): create form component
  web-components/src/[sandbox]/examples/form.ts
  web-components/src/[sandbox]/examples/index.ts
  web-components/src/[sandbox]/sandbox.ts
  web-components/src/components/form/Form.stories.ts
  web-components/src/components/form/Form.test.ts
  web-components/src/components/form/Form.ts
  web-components/src/components/input/Input.ts
Labels: REVIEW, new component

#779 refactor(form): update form
  web-components/src/[sandbox]/examples/form.ts
  web-components/src/components/combobox/ComboBox.stories.ts
  web-components/src/components/form/Form.stories.ts
  web-components/src/components/form/Form.test.ts
  web-components/src/components/form/Form.ts
  web-components/src/index.ts
  web-components/src/mixins/CustomElementCheck.ts
  web-components/src/mixins/index.ts
  web-components/webpack.config.ts
Labels: REVIEW, docs, enhancement

#776 feat(draggable): add new draggable component
  web-components/.storybook/main.ts
  web-components/.storybook/preview-body.html
  web-components/package.json
  web-components/src/[sandbox]/examples/combobox.ts
  web-components/src/[sandbox]/examples/draggable.ts
  web-components/src/[sandbox]/examples/index.ts
  web-components/src/[sandbox]/sandbox.mock.ts
  web-components/src/[sandbox]/sandbox.ts
  web-components/src/components/combobox/ComboBox.ts
  web-components/src/components/draggable/Draggable.mdx
  web-components/src/components/draggable/Draggable.stories.ts
  web-components/src/components/draggable/Draggable.test.ts
  web-components/src/components/draggable/Draggable.ts
  web-components/src/components/draggable/DraggableItem.test.ts
  web-components/src/components/draggable/DraggableItem.ts
  web-components/src/components/draggable/scss/draggable-item.scss
  web-components/src/components/draggable/scss/module.scss
  web-components/src/components/draggable/scss/settings.scss
  web-components/src/components/menu-overlay/MenuOverlay.test.ts
  web-components/src/constants.ts
  web-components/src/index.ts
  web-components/src/mixins/FocusTrapMixin.test.ts
  web-components/src/mixins/index.ts
  web-components/src/types/declare.d.ts
  web-components/src/utils/dateUtils.test.ts
  web-components/src/utils/enums.ts
  web-components/src/utils/validations.ts
  web-components/webpack.config.ts
Labels: REVIEW, new component, web component

#781 docs(*): fix ESLint warnings
  web-components/src/[sandbox]/examples/badge.ts
  web-components/src/[sandbox]/examples/button-group.ts
  web-components/src/[sandbox]/examples/card.ts
  web-components/src/[sandbox]/examples/chat-message.ts
  web-components/src/[sandbox]/examples/coachmark.ts
  web-components/src/[sandbox]/examples/date-time-picker.ts
  web-components/src/[sandbox]/examples/datepicker.ts
  web-components/src/[sandbox]/examples/editable-field.ts
  web-components/src/[sandbox]/examples/favorite.ts
  web-components/src/[sandbox]/examples/form.ts
  web-components/src/[sandbox]/examples/input.ts
  web-components/src/[sandbox]/examples/meeting-alert.ts
  web-components/src/[sandbox]/examples/menu-item.ts
  web-components/src/[sandbox]/examples/menu-overlay.ts
  web-components/src/[sandbox]/examples/modal.ts
  web-components/src/[sandbox]/examples/table.ts
  web-components/src/[sandbox]/examples/tabs.ts
  web-components/src/[sandbox]/examples/timepicker.ts
  web-components/src/[sandbox]/sandbox.scss
Labels: docs, enhancement

#784 Kehyde/date range picker
  web-components/codecov.yml
  web-components/src/[sandbox]/examples/date-range-picker.ts
  web-components/src/[sandbox]/examples/date-time-picker.ts
  web-components/src/[sandbox]/examples/index.ts
  web-components/src/[sandbox]/sandbox.ts
  web-components/src/components/date-range-picker/DateRangePicker.stories.ts
  web-components/src/components/date-range-picker/DateRangePicker.test.ts
  web-components/src/components/date-range-picker/DateRangePicker.ts
  web-components/src/components/date-range-picker/scss/daterangepicker.scss
  web-components/src/components/date-range-picker/tokens/lm-date-range-picker-tokens.js
  web-components/src/components/date-range-picker/tokens/md-date-range-picker-tokens.js
  web-components/src/components/datepicker/DatePicker.ts
  web-components/src/components/datepicker/datepicker-calendar/DatePickerCalendar.ts
  web-components/src/components/datepicker/datepicker-day/DatePickerDay.ts
  web-components/src/components/datepicker/datepicker-month/DatePickerMonth.ts
  web-components/src/components/datepicker/datepicker-week/DatePickerWeek.ts
  web-components/src/components/datepicker/scss/datepicker.scss
  web-components/src/components/datepicker/tokens/lm-datepicker-tokens.js
  web-components/src/components/datepicker/tokens/md-datepicker-tokens.js
  web-components/src/index.ts
  web-components/src/utils/helpers.ts
  web-components/src/utils/validations.ts
  web-components/webpack.config.ts
Labels: enhancement, in progress, web component

#795 fix(radio): repair style with class name edit
  web-components/src/components/radio/Radio.ts
Labels: bug, web component
