Repository momentum-design/momentum-ui, pull requests merged in 2021-01, with the labels that each got.

#744 fix(floating-modal): fix floating modal expand/collapse position
  web-components/src/[sandbox]/examples/floating-modal.ts
  web-components/src/components/floating-modal/FloatingModal.ts
Labels: REVIEW, bug

#725 feat(component): create card component
  web-components/src/[sandbox]/examples/card.ts
  web-components/src/[sandbox]/examples/index.ts
  web-components/src/[sandbox]/sandbox.ts
  web-components/src/components/card/Card.ts
  web-components/src/components/card/scss/card.scss
  web-components/src/components/card/scss/module.scss
  web-components/src/components/card/scss/settings.scss
  web-components/src/index.ts
Labels: WIP, new component

#732 Create menu item component
  web-components/src/[sandbox]/examples/index.ts
  web-components/src/[sandbox]/examples/menu-item.ts
  web-components/src/[sandbox]/sandbox.ts
  web-components/src/components/menu-overlay/MenuOverlay.ts
  web-components/src/components/menu/Menu.stories.ts
  web-components/src/components/menu/Menu.test.ts
  web-components/src/components/menu/Menu.ts
  web-components/src/components/menu/MenuItem.test.ts
  web-components/src/components/menu/MenuItem.ts
  web-components/src/components/menu/scss/menu-item.scss
  web-components/src/components/menu/scss/menu.scss
  web-components/src/components/menu/scss/module.scss
  web-components/src/components/menu/scss/settings.scss
  web-components/src/components/menu/tokens/lm-menu-tokens.js
  web-components/src/components/menu/tokens/md-menu-tokens.js
  web-components/src/components/theme/Theme.ts
  web-components/src/index.ts
Labels: new component

#747 CAX-865 - Add new color to badge and chips component
  web-components/src/[sandbox]/examples/badge.ts
  web-components/src/[sandbox]/examples/chip.ts
  web-components/src/components/badge/scss/badge.scss
  web-components/src/components/badge/tokens/lm-badge-tokens.js
  web-components/src/components/badge/tokens/md-badge-tokens.js
  web-components/src/components/chip/scss/chip.scss
Labels: REVIEW

#749 fix(floating-modal): fix start position
  web-components/src/components/floating-modal/FloatingModal.ts
Labels: REVIEW, bug

#754 fix(tooltip): change re-rendering logic on data change
  web-components/src/[sandbox]/examples/tooltip.ts
  web-components/src/components/theme/Theme.ts
  web-components/src/components/tooltip/Tooltip.ts
Labels: REVIEW, bug

#751 fix(DateTimePicker): fix month navigation, initial values, input field modification
  web-components/src/[sandbox]/examples/date-time-picker.ts
  web-components/src/[sandbox]/examples/datepicker.ts
  web-components/src/components/date-time-picker/DateTimePicker.ts
  web-components/src/components/datepicker/DatePicker.test.ts
  web-components/src/components/datepicker/DatePicker.ts
  web-components/src/components/datepicker/datepicker-calendar/DatePickerCalendar.ts
  web-components/src/components/datepicker/scss/datepicker.scss
  web-components/src/components/input/Input.ts
  web-components/src/components/timepicker/TimePicker.stories.ts
  web-components/src/components/timepicker/TimePicker.ts
  web-components/src/utils/validations.ts
Labels: REVIEW

#756 fix(combobox): improve performance for non-multi select
  web-components/src/components/combobox/ComboBox.ts
Labels: REVIEW

#755 fix(secondary label): fix secondary label position
  web-components/src/components/label/Label.ts
  web-components/src/components/label/scss/label.scss
  web-components/src/components/label/scss/mixins.scss
  web-components/src/components/label/scss/module.scss
  web-components/src/components/label/scss/settings.scss
Labels: REVIEW

#753 feat(input file): create input file component
  web-components/package.json
  web-components/src/[sandbox]/examples/index.ts
  web-components/src/[sandbox]/examples/input-file.ts
  web-components/src/[sandbox]/sandbox.ts
  web-components/src/components/input-file/InputFile.stories.ts
  web-components/src/components/input-file/InputFile.test.ts
  web-components/src/components/input-file/InputFile.ts
  web-components/src/components/input-file/scss/input-file.scss
  web-components/src/components/input-file/scss/module.scss
  web-components/src/index.ts
  web-components/src/types/declare.d.ts
Labels: REVIEW, new component

#734 feat(code-editor): create code-editor component
  web-components/package.json
  web-components/src/[sandbox]/examples/code-editor.ts
  web-components/src/[sandbox]/examples/index.ts
  web-components/src/[sandbox]/sandbox.ts
  web-components/src/components/code-editor/CodeEditor.stories.ts
  web-components/src/components/code-editor/CodeEditor.test.ts
  web-components/src/components/code-editor/CodeEditor.ts
  web-components/src/components/code-editor/scss/code-editor.scss
  web-components/src/components/code-editor/scss/module.scss
  web-components/src/components/code-editor/scss/settings.scss
  web-components/src/index.ts
Labels: REVIEW, new component

#750 Add Favorite toggle component
  web-components/src/[sandbox]/examples/favorite.ts
  web-components/src/[sandbox]/examples/index.ts
  web-components/src/[sandbox]/sandbox.ts
  web-components/src/components/button/scss/button.scss
  web-components/src/components/button/tokens/lm-button-tokens.js
  web-components/src/components/favorite/Favorite.stories.ts
  web-components/src/components/favorite/Favorite.test.ts
  web-components/src/components/favorite/Favorite.ts
  web-components/src/components/favorite/scss/favorite.scss
  web-components/src/components/favorite/scss/module.scss
  web-components/src/components/favorite/scss/settings.scss
  web-components/src/index.ts
Labels: REVIEW, new component

#764 fix(tooltip): fix tooltip appearance after trigger disconnected from DOM
  web-components/src/[sandbox]/examples/tooltip.ts
  web-components/src/[sandbox]/sandbox.ts
  web-components/src/components/theme/Theme.ts
  web-components/src/components/tooltip/Tooltip.ts
Labels: REVIEW, bug
